### ISSUE TITLE
repo name

### ISSUE THREAD

**Issue by nimit2801** [hardikraval1324/ColorChangeJs#1]
The repo name, to be honest, looks weird, because it has `-` at the end, you can change the repo name to makes this repo more attractive and you can add this project to your list.

Suggestion: `ColorChangeJs`

**Comment by hardikraval1324** [comment]
Yeah thanks for the name 😉

**Comment by hardikraval1324** [comment]
Done

**Comment by hardikraval1324** [comment]
Done 👍
